CREATE TABLE STAFF (
	STAFF_ID INT IDENTITY(1,1) PRIMARY KEY,
	STAFF_NAME VARCHAR(50),
	USERNAME VARCHAR(20) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	PASSWORD VARCHAR(50) NOT NULL,
	DESIGNATION VARCHAR(20),
	ACCESS_LEVEL VARCHAR(15) NOT NULL,
	STATUS VARCHAR(10),
	DEPART_ALIAS VARCHAR(10) NOT NULL,

)